/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 23:32:53 GMT 2022
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.TextNode;
import org.jsoup.nodes.XmlDeclaration;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class LeafNode_ESTest extends LeafNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("declare", "R4XK.Tt");
      Document document0 = new Document("declare");
      dataNode0.setParentNode(document0);
      dataNode0.baseUri();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("declare", "R4XK.Tt");
      dataNode0.baseUri();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", true);
      xmlDeclaration0.attr("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("`8Z's?06xU", "-}u!/5", "-}u!/5");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("H4", true);
      xmlDeclaration0.doSetBaseUri("");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TextNode textNode0 = new TextNode("", "");
      textNode0.text("");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("G!3Yi\"T-OJLab&lm%", true);
      xmlDeclaration0.absUrl(" Kh\"");
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      DataNode dataNode0 = new DataNode("Failed after {}: {}");
      // Undeclared exception!
      try { 
        dataNode0.ensureChildNodes();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Leaf Nodes do not have child nodes.
         //
         verifyException("org.jsoup.nodes.LeafNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Comment comment0 = new Comment("*:.Ii%=");
      comment0.removeAttr("*:.Ii%=");
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      DataNode dataNode0 = DataNode.createFromEncoded("G!3Yi\"T-OJLab&lm%", "G!3Yi\"T-OJLab&lm%");
      dataNode0.toString();
  }
}
