/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 23:37:04 GMT 2022
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.CDataNode;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CDataNode_ESTest extends CDataNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("%Y(vNYD[Bj|/1}}:OL");
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) "%Y(vNYD[Bj|/1}}:OL");
      stringBuilder0.append((Object) cDataNode0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      cDataNode0.text();
      assertEquals("#cdata", cDataNode0.nodeName());
  }
}
