/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 23:35:56 GMT 2022
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.PseudoTextElement;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PseudoTextElement_ESTest extends PseudoTextElement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tag tag0 = mock(Tag.class, new ViolatedAssumptionAnswer());
      Attributes attributes0 = mock(Attributes.class, new ViolatedAssumptionAnswer());
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "KFEo!JYj:", attributes0);
      Document.OutputSettings document_OutputSettings0 = pseudoTextElement0.getOutputSettings();
      pseudoTextElement0.outerHtmlHead((Appendable) null, 2707, document_OutputSettings0);
  }
}
