/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 22 23:36:43 GMT 2022
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.select.Collector;
import org.jsoup.select.Elements;
import org.jsoup.select.Evaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Collector_ESTest extends Collector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Evaluator evaluator0 = mock(Evaluator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(evaluator0).matches(any(org.jsoup.nodes.Element.class) , any(org.jsoup.nodes.Element.class));
      Node node0 = mock(Node.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(node0).childNodeSize();
      doReturn((Node) null).when(node0).nextSibling();
      doReturn((Node) null).when(node0).parentNode();
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn(1729).when(element0).childNodeSize();
      doReturn(node0).when(element0).childNode(anyInt());
      // Undeclared exception!
      try { 
        Collector.findFirst(evaluator0, element0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.NodeTraversor", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Evaluator evaluator0 = mock(Evaluator.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(evaluator0).matches(any(org.jsoup.nodes.Element.class) , any(org.jsoup.nodes.Element.class));
      Node node0 = mock(Node.class, new ViolatedAssumptionAnswer());
      doReturn(0).when(node0).childNodeSize();
      doReturn((Node) null).when(node0).nextSibling();
      doReturn((Node) null).when(node0).parentNode();
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn(1).when(element0).childNodeSize();
      doReturn((String) null).when(element0).toString();
      doReturn(node0).when(element0).childNode(anyInt());
      Element element1 = Collector.findFirst(evaluator0, element0);
      Evaluator evaluator1 = mock(Evaluator.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(evaluator1).matches(any(org.jsoup.nodes.Element.class) , any(org.jsoup.nodes.Element.class));
      // Undeclared exception!
      try { 
        Collector.collect(evaluator1, element1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.NodeTraversor", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Evaluator evaluator0 = mock(Evaluator.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(evaluator0).matches(any(org.jsoup.nodes.Element.class) , any(org.jsoup.nodes.Element.class));
      Node node0 = mock(Node.class, new ViolatedAssumptionAnswer());
      Element element0 = mock(Element.class, new ViolatedAssumptionAnswer());
      doReturn((-86)).when(element0).childNodeSize();
      doReturn((String) null).when(element0).toString();
      doReturn(node0).when(element0).nextSibling();
      Element element1 = Collector.findFirst(evaluator0, element0);
      Evaluator evaluator1 = mock(Evaluator.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(evaluator1).matches(any(org.jsoup.nodes.Element.class) , any(org.jsoup.nodes.Element.class));
      Elements elements0 = Collector.collect(evaluator1, element1);
      assertTrue(elements0.isEmpty());
  }
}
